default:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  host: localhost
  username: asad
  password: asad
development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  host: localhost
  username: asad
  password: asad
test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  host: localhost
  username: asad
  password: asad

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
